[ Fix ] *** Seems like you are using `yarn` which is not supported in this repo any more, please use `npm i` instead. ***

diff --git a/.github/workflows/codeoss-ci.yml b/.github/workflows/codeoss-ci.yml
--- a/.github/workflows/codeoss-ci.yml
+++ b/.github/workflows/codeoss-ci.yml
@@ -142,12 +142,12 @@ jobs:
         if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
         run: |
           for i in {1..5}; do # try 5 times
-            yarn --frozen-lockfile --check-files && break
-            if [ "$i" -eq 3 ]; then
-              echo "Yarn failed too many times" >&2
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
               exit 1
             fi
-            echo "Yarn failed $i, trying again..."
+            echo "Npm install failed $i, trying again..."
           done
         env:
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
@@ -301,65 +301,27 @@ jobs:
 
       - name: Install build dependencies
         run: |
-          node build/npm/setupBuildYarnrc
-          for i in {1..3}; do
-          	yarn --cwd build --frozen-lockfile --check-files && break
-          	if [ "$i" -eq 3 ]; then
-          		echo "Yarn failed too many times" >&2
-          		exit 1
-          	fi
-          	echo "Yarn failed $i, trying again..."
+          for i in {1..5}; do # try 5 times
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
+              exit 1
+            fi
+            echo "Npm install failed $i, trying again..."
           done
 
       - name: Install dependencies
         if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
         run: |
-          if [ "$NPM_ARCH" = "armv7l" ]; then
-          	# There is no target_arch="armv7l" supported by node_gyp,
-          	# arm versions for compilation are decided based on the CC
-          	# macros.
-          	# Mapping value is based on
-          	# https://github.com/nodejs/node/blob/0903515e126c2697042d6546c6aa4b72e1a4b33e/configure.py#L49-L50
-          	npm_config_arch="arm"
-          else
-          	npm_config_arch=$NPM_ARCH
-          fi
-          export npm_config_arch
+          source ./build/azure-pipelines/linux/setup-env.sh
 
-          if [ -z "$CC" ] || [ -z "$CXX" ]; then
-          	# Download clang based on chromium revision used by vscode
-          	curl -s https://raw.githubusercontent.com/chromium/chromium/98.0.4758.109/tools/clang/scripts/update.py |
-          		python - --output-dir="$PWD"/.build/CR_Clang --host-os=linux
-          	# Download libcxx headers and objects from upstream electron releases
-          	DEBUG=libcxx-fetcher \
-          		VSCODE_LIBCXX_OBJECTS_DIR=$PWD/.build/libcxx-objects \
-          		VSCODE_LIBCXX_HEADERS_DIR=$PWD/.build/libcxx_headers \
-          		VSCODE_LIBCXXABI_HEADERS_DIR=$PWD/.build/libcxxabi_headers \
-          		VSCODE_ARCH="$NPM_ARCH" \
-          		node build/linux/libcxx-fetcher.js
-          	# Set compiler toolchain
-          	# Flags for the client build are based on
-          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.109:build/config/arm.gni
-          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.109:build/config/compiler/BUILD.gn
-          	# https://source.chromium.org/chromium/chromium/src/+/refs/tags/98.0.4758.109:build/config/c++/BUILD.gn
-
-          	export CC="$PWD"/.build/CR_Clang/bin/clang
-          	export CXX="$PWD"/.build/CR_Clang/bin/clang++
-          	export CXXFLAGS="-nostdinc++ -D__NO_INLINE__ -isystem$PWD/.build/libcxx_headers -isystem$PWD/.build/libcxx_headers/include -isystem$PWD/.build/libcxxabi_headers/include -fPIC -flto=thin -fsplit-lto-unit"
-          	export LDFLAGS="-stdlib=libc++ -fuse-ld=lld -flto=thin -L$PWD/.build/libcxx-objects -lc++abi -Wl,--lto-O0"
-          	# shellcheck disable=SC2155
-          	export VSCODE_REMOTE_CC="$(which gcc)"
-          	# shellcheck disable=SC2155
-          	export VSCODE_REMOTE_CXX="$(which g++)"
-          fi
-
-          for i in {1..3}; do
-          	yarn --frozen-lockfile --check-files && break
-          	if [ "$i" -eq 3 ]; then
-          		echo "Yarn failed too many times" >&2
-          		exit 1
-          	fi
-          	echo "Yarn failed $i, trying again..."
+          for i in {1..5}; do # try 5 times
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
+              exit 1
+            fi
+            echo "Npm install failed $i, trying again..."
           done
         env:
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
@@ -602,12 +564,12 @@ jobs:
           export npm_config_node_gyp
 
           for i in {1..5}; do # try 5 times
-            yarn --frozen-lockfile --check-files && break
-            if [ $i -eq 3 ]; then
-              echo "Yarn failed too many times" >&2
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
               exit 1
             fi
-            echo "Yarn failed $i, trying again..."
+            echo "Npm install failed $i, trying again..."
           done
         env:
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
@@ -846,13 +808,13 @@ jobs:
           CHILD_CONCURRENCY="1"
           export CHILD_CONCURRENCY
 
-          for i in {1..3}; do
-          	yarn --frozen-lockfile --check-files && break
-          	if [ "$i" -eq 3 ]; then
-          		echo "Yarn failed too many times" >&2
-          		exit 1
-          	fi
-          	echo "Yarn failed $i, trying again..."
+          for i in {1..5}; do # try 5 times
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
+              exit 1
+            fi
+            echo "Npm install failed $i, trying again..."
           done
         env:
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
@@ -1013,12 +975,12 @@ jobs:
         if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
         run: |
           for i in {1..5}; do # try 5 times
-            yarn --frozen-lockfile --check-files && break
-            if [ $i -eq 3 ]; then
-              echo "Yarn failed too many times" >&2
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
               exit 1
             fi
-            echo "Yarn failed $i, trying again..."
+            echo "Npm install failed $i, trying again..."
           done
         env:
           ELECTRON_SKIP_BINARY_DOWNLOAD: 1
